name: Gatsby Publish

on:
  release:
    types:
      - released

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node installieren & Build
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: cd gatsby
      - run: npm i
      - run: npm run build
      - run: npm run deploy
